@include('front.head')
@include('front.navbar')
@include('front.carousel')
{{-- @include('front.fact') --}}
@include('front.about')
@include('front.services')
@include('front.projects')
@include('front.blog')
@include('front.team')
@include('front.testimonial')
@include('front.contact')
@include('front.footer')
